### ISSUE TITLE
ERROR: Failed to resolve: com.github.PhilJay:MPAndroidChart:v3.1.0

### ISSUE THREAD

**Issue by EleNikIvi** [stfalcon-studio/StfalconPriceRangeBar-android#10]
after adding implementation 'com.github.stfalcon:StfalconPriceRangeBar:0.1.1' as dependency, I got next error:

ERROR: Failed to resolve: com.github.PhilJay:MPAndroidChart:v3.1.0
Show in Project Structure dialog
Affected Modules: app

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutinesVersion"

    implementation "androidx.core:core-ktx:$ktxVersion"

    implementation "org.koin:koin-core:$koinVersion"
    implementation "org.koin:koin-core-ext:$koinVersion"
    implementation "org.koin:koin-android:$koinVersion"
    implementation "org.koin:koin-androidx-scope:$koinVersion"
    implementation "org.koin:koin-androidx-viewmodel:$koinVersion"

    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycleVersion"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycleVersion"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycleVersion"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    implementation "androidx.appcompat:appcompat:$appCompatVersion"
    implementation "androidx.fragment:fragment:$fragmentVersion"
    implementation "androidx.fragment:fragment-ktx:$fragmentVersion"
    implementation "androidx.constraintlayout:constraintlayout:$constraintLayoutVersion"
    implementation "com.google.android.material:material:$materialVersion"

    implementation "com.google.android.gms:play-services-location:$playServicesVersion"

    implementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
    implementation "com.squareup.retrofit2:converter-moshi:$retrofitVersion"
    implementation "com.squareup.okhttp3:logging-interceptor:$okHttpLoggingVersion"
    implementation "com.squareup.moshi:moshi:$moshiVersion"
    implementation "com.squareup.moshi:moshi-kotlin:$moshiVersion"
    kapt("com.squareup.moshi:moshi-kotlin-codegen:$moshiVersion")

    implementation "com.airbnb.android:epoxy:$epoxyVersion"
    kapt "com.airbnb.android:epoxy-processor:$epoxyVersion"

    implementation "com.github.bumptech.glide:glide:$glideVersion"
    annotationProcessor "com.github.bumptech.glide:compiler:$glideVersion"

    implementation "com.jakewharton.timber:timber:$timberVersion"
    implementation 'com.romandanylyk:pageindicatorview:1.0.3'

    implementation "com.airbnb.android:epoxy:$epoxyVersion"
    kapt "com.airbnb.android:epoxy-processor:$epoxyVersion"
    implementation "com.crashlytics.sdk.android:crashlytics:$crashlyticsVersion"
    implementation 'com.facebook.shimmer:shimmer:0.4.0'
    implementation 'com.github.stfalcon:StfalconPriceRangeBar:0.1.1'

    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$extJunitVersion"
    androidTestImplementation "androidx.test:runner:$testRunnerVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espressoVersion"
}

**Comment by andriizhumela** [comment]
Hi @EleNikIvi 
Could you send me full content from gradle file?

**Comment by EleNikIvi** [comment]
@andriizhumela 
Project gradle:
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        kotlin_version = '1.3.50'
        nav_version = '2.2.0-alpha02'
    }
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
        classpath 'com.google.gms:google-services:4.3.2'
        classpath 'io.fabric.tools:gradle:1.31.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()

    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


app gradle:

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'androidx.navigation.safeargs.kotlin'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

ext {
    coroutinesVersion = '1.3.0'
    ktxVersion = '1.2.0-alpha04'
    koinVersion = '2.0.1'

    lifecycleVersion = '2.1.0'

    appCompatVersion = '1.1.0'
    fragmentVersion = '1.2.0-alpha03'
    fragmentKtxVersion = '1.1.0-rc01'
    constraintLayoutVersion = '1.1.3'
    materialVersion = '1.1.0-alpha10'

    playServicesVersion = '17.0.0'

    retrofitVersion = '2.6.1'
    okHttpLoggingVersion = '4.1.0'
    moshiVersion = '1.8.0'

    epoxyVersion = '3.3.1'

    glideVersion = '4.9.0'

    timberVersion = '4.7.1'

    epoxyVersion = '3.3.1'

    junitVersion = '4.12'
    extJunitVersion = '1.1.1'
    testRunnerVersion = '1.2.0'
    espressoVersion = '3.2.0'

    crashlyticsVersion = '2.10.1'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutinesVersion"

    implementation "androidx.core:core-ktx:$ktxVersion"

    implementation "org.koin:koin-core:$koinVersion"
    implementation "org.koin:koin-core-ext:$koinVersion"
    implementation "org.koin:koin-android:$koinVersion"
    implementation "org.koin:koin-androidx-scope:$koinVersion"
    implementation "org.koin:koin-androidx-viewmodel:$koinVersion"

    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycleVersion"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycleVersion"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycleVersion"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    implementation "androidx.appcompat:appcompat:$appCompatVersion"
    implementation "androidx.fragment:fragment:$fragmentVersion"
    implementation "androidx.fragment:fragment-ktx:$fragmentVersion"
    implementation "androidx.constraintlayout:constraintlayout:$constraintLayoutVersion"
    implementation "com.google.android.material:material:$materialVersion"

    implementation "com.google.android.gms:play-services-location:$playServicesVersion"

    implementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
    implementation "com.squareup.retrofit2:converter-moshi:$retrofitVersion"
    implementation "com.squareup.okhttp3:logging-interceptor:$okHttpLoggingVersion"
    implementation "com.squareup.moshi:moshi:$moshiVersion"
    implementation "com.squareup.moshi:moshi-kotlin:$moshiVersion"
    kapt("com.squareup.moshi:moshi-kotlin-codegen:$moshiVersion")

    implementation "com.airbnb.android:epoxy:$epoxyVersion"
    kapt "com.airbnb.android:epoxy-processor:$epoxyVersion"

    implementation "com.github.bumptech.glide:glide:$glideVersion"
    annotationProcessor "com.github.bumptech.glide:compiler:$glideVersion"

    implementation "com.jakewharton.timber:timber:$timberVersion"
    implementation 'com.romandanylyk:pageindicatorview:1.0.3'

    implementation "com.airbnb.android:epoxy:$epoxyVersion"
    kapt "com.airbnb.android:epoxy-processor:$epoxyVersion"
    implementation "com.crashlytics.sdk.android:crashlytics:$crashlyticsVersion"
    implementation 'com.facebook.shimmer:shimmer:0.4.0'
    implementation 'com.github.stfalcon:StfalconPriceRangeBar:0.1.1'

    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$extJunitVersion"
    androidTestImplementation "androidx.test:runner:$testRunnerVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espressoVersion"
}

apply plugin: 'com.google.gms.google-services'

**Comment by EleNikIvi** [comment]
I found a solution. It was necessary to add maven repository to project gradle file:
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
