### ISSUE TITLE
Reload already selected values

### ISSUE THREAD

**Issue by MustanserIqbal93** [stfalcon-studio/StfalconPriceRangeBar-android#12]
Is there any way to reload already selected values?

Let say i have price range between 1-100

User have selected 10-30. 

Now can i load 10-30 when user navigate for 2nd time?

**Comment by andriizhumela** [comment]
Hi @MustanserIqbal93 . In this moment we can't pre-select any values. 
It will we added in the next version.

**Comment by MustanserIqbal93** [comment]
Hi, tanks for the response. Can you let me know when you are planning for next version? Thanks

**Comment by andriizhumela** [comment]
@MustanserIqbal93 Added in version 0.1.3

**Comment by MustanserIqbal93** [comment]
Thanks for this addition but the selection is not working as expected. When i use setSelectedEntries method then it select some random numbers on bar chart.
