### ISSUE TITLE
Error on adding dependency

### ISSUE THREAD

**Issue by Nataanthoni** [stfalcon-studio/StfalconPriceRangeBar-android#14]
The library cannot be added as i get the below error;

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.PhilJay:MPAndroidChart:v3.1.0.
     Required by:
         project :app > com.github.stfalcon:StfalconPriceRangeBar:0.1.3

**Comment by andriizhumela** [comment]
Hi @Nataanthoni 
Please, try to add repo:
```
repositories {
    maven { url 'https://jitpack.io' }
}
```

**Comment by Nataanthoni** [comment]
Yes, i did ... i added it to build.gradle and i get the below error;
ERROR: Failed to resolve: com.github.PhilJay:MPAndroidChart:v3.1.0
Show in Project Structure dialog
Affected Modules: app

**Comment by Nataanthoni** [comment]
> Hi @Nataanthoni
> Please, try to add repo:
> 
> ```
> repositories {
>     maven { url 'https://jitpack.io' }
> }
> ```

Please, disregard my previous response. it finally worked. Thanks :)
