### ISSUE TITLE
Error inflating class com.stfalcon.pricerangebar.SeekBarWithChart

### ISSUE THREAD

**Issue by VitalySizov** [stfalcon-studio/StfalconPriceRangeBar-android#2]
An error occurs:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test/com.example.test.MainActivity}: android.view.InflateException: Binary XML file line #58: Binary XML file line #58: Error inflating class com.stfalcon.pricerangebar.SeekBarWithChart

class MainActivity : AppCompatActivity() {

    private var seekBarEntries = ArrayList<BarEntry>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val barEntrys = ArrayList<BarEntry>()

        seekBarEntries.add(BarEntry(30.0f, 5.0f))
        seekBarEntries.add(BarEntry(32.0f, 7.0f))
        seekBarEntries.add(BarEntry(34.0f, 10.0f))
        seekBarEntries.add(BarEntry(36.0f, 11.0f))
        seekBarEntries.add(BarEntry(38.0f, 14.0f))
        seekBarEntries.add(BarEntry(40.0f, 15.0f))

        seekBar.setEntries(barEntrys)
    }
} 

XML:

<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            xmlns:tools="http://schemas.android.com/tools"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
                                                 xmlns:app="http://schemas.android.com/apk/res-auto"
                                                 xmlns:tools="http://schemas.android.com/tools"
                                                 android:layout_width="match_parent"
                                                 android:layout_height="wrap_content"
                                                 tools:context=".MainActivity">

        <TextView
                android:id="@+id/seekbarAreaTitle"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="21dp"
                android:layout_marginTop="16dp"
                android:layout_marginEnd="21dp"
                android:text="Area"
                android:textColor="@android:color/black"
                android:textSize="24sp"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

        <TextView
                android:id="@+id/seekbarAreaValue"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="21dp"
                android:layout_marginTop="16dp"
                android:layout_marginEnd="21dp"
                tools:text="50 m"
                android:textColor="@android:color/black"
                android:textSize="24sp"
                android:textStyle="bold"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/seekbarAreaTitle" />

        <TextView
                android:id="@+id/seekbarAreaInfo"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="21dp"
                android:layout_marginTop="16dp"
                android:layout_marginEnd="21dp"
                android:textColor="@android:color/black"
                android:textSize="12sp"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/seekbarAreaValue"
                tools:text="18 elements was selected" />

        <com.stfalcon.pricerangebar.SeekBarWithChart
                android:id="@+id/seekBar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="21dp"
                android:layout_marginTop="16dp"
                android:layout_marginEnd="21dp"
                app:layout_constraintTop_toBottomOf="@+id/seekbarAreaInfo"
        />
    </android.support.constraint.ConstraintLayout>
</ScrollView>

In dependencies:
implementation 'com.github.stfalcon:StfalconPriceRangeBar:0.1.0'

**Comment by andriizhumela** [comment]
I will check this issue as soon as possible

**Comment by emailsubjekt** [comment]
Is this solved? I'm not getting any errors. Also, it's a cool project and thank you. Can you make a java version instead of kotlin?

**Comment by walkingice** [comment]
@VitalySizov Did you set `android.useAndroidX = true` in your repository?

I got the same error. And add SeekBarWithCart source code to my own repository then import ConstraintLayout from android-x. Which fixed my problem.

**Comment by andriizhumela** [comment]
Fixed in version 0.1.1
