### ISSUE TITLE
Can you make a Java version - not an error

### ISSUE THREAD

**Issue by emailsubjekt** [stfalcon-studio/StfalconPriceRangeBar-android#5]
I love your project and was wondering if a java implementation is possible?

**Comment by andriizhumela** [comment]
Hi @emailsubjekt, did you read [this article](https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html)?

**Comment by emailsubjekt** [comment]
> Hi @emailsubjekt, did you read [this article](https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html)?

I know but why.  It just seems the complicated way to go. I can also convert kotlin to java but it usually doesn't do it right. I would also have to convert all the classes composing this library. The maker of the library would do it far better knowing what to do. I'm working on completely different parts of java and don't have time right now to go into kotlin plus it seems really non intuitive. Unlike java it's not straightforward.

**Comment by andriizhumela** [comment]
Unfortunately, there are no plans to release the version of Java.

**Comment by emailsubjekt** [comment]
Too bad, kotlin just seems like a waste of time. Java is the real language, kotlin is just like java with shortened phrases instead of full names. That's how I see it. Everything should be in java not kotlin.
