### ISSUE TITLE
java version would be nice

### ISSUE THREAD

**Issue by cpbentley** [stfalcon-studio/StfalconPriceRangeBar-android#6]
We use Java.

Kotlin is overkill.

Might port it to Java if none.

**Comment by emailsubjekt** [comment]
I completely agree. Kotlin just sucks, the only thing good about it is you can reference directly from xml. But this is completely unnecessary.

**Comment by andriizhumela** [comment]
But, you can use it from Java. Here here is a small [example](https://github.com/stfalcon-studio/StfalconPriceRangeBar-android#how-to-use-it-in-java).
