### ISSUE TITLE
ERROR: Failed to resolve: com.github.PhilJay:MPAndroidChart:v3.1.0

### ISSUE THREAD

**Issue by emailsubjekt** [stfalcon-studio/StfalconPriceRangeBar-android#8]
This is the message I get when I add 
implementation 'com.github.stfalcon:StfalconPriceRangeBar:0.1.1'
to Gradle

ERROR: Failed to resolve: com.github.PhilJay:MPAndroidChart:v3.1.0
Show in Project Structure dialog
Affected Modules: app

**Comment by emailsubjekt** [comment]
I'm using AndroidX, I don't know if that has anything to do with it?

**Comment by emailsubjekt** [comment]
I've resolved it, bintray is the culprit, to be exact, it's version in build.gradle

**Comment by EleNikIvi** [comment]
> I've resolved it, bintray is the culprit, to be exact, it's version in build.gradle

Could you, please, explain, how you fix it? I have the same error...

**Comment by emailsubjekt** [comment]
It's using kotlin, I wouldn't advise using it, it's a piece of s*it language that should be shot in the head and just left to die by the road. If you could port it to java I'll give you the solution. Answer back.

**Comment by Diegitsen** [comment]
Kotlin is much better than java
